<main id="options">

	<section id="form">
	<form action="modifier.php" method="POST" >
		<label for="nickname">Pseudo: </label>
		<input type="text" name="nickname"  disabled value=<?php echo $pseudo?> />
		<br/>
		<label for="email">Adresse Mail: </label>
		<input type="email" name="email"  disabled value=<?php echo $email ?>>
		<br/>
		<label for="motDePasse">Mot de passe:</label>
		<input type="password" disabled name="motDePasse" />
		<br/>
		<label for="sexe">Sexe: </label>
		<select type="text" name="sexe"  >
			<?php if ($genre=="Woman"): ?>
			<option value="Man">Homme</option>
			<option value="Woman" selected=selected>Femme</option>
			<?php endif?>
			
			<?php if ($genre=="Man"): ?>
			<option value="Man" selected=selected>Homme</option>
			<option value="Woman">Femme</option>
			<?php endif?>
			
		</select>	
		<br/>
		<label for="prenom">Prenom: </label>
		<input type="text" name="prenom" value=<?php echo $prenom ?>>
		<br/>
		<label for="nom">Nom: </label>
		<input type="text" name="nom" value=<?php echo $nom ?> >
		<br/>
		<label for="birth">Date de naissance: </label>
		<input id="anniv" type="date" name="birth" value=<?php echo $birth ?> >
		<br/>
		<label for="adresse">Adresse: </label>
		<input type="text" name="adresse" value=<?php echo $adresse ?> >
		<br/>
		<label for="zip">Code Postal: </label>
		<input id="zip" type="text" name="zip" value=<?php echo $zipCode ?> >
		<br/>
		<div id="aCacher">
		<label for="city">Ville:  </label>
		<select id="city" name="city">
		</select>
		</div>
		<br/>
		<br/>
		<input id="bouton" type="submit" value="Modifier"/>
		</form>
	</section>
	
	<section id="parametres">
		
	</section>
		
</main>